### ISSUE TITLE
Неактивная ссылка на статью по теории тестирования в материалах первой лекции 

### ISSUE THREAD

**Issue by dinakazakevich** [volekerb/testing-lectures#5]
Неактивная ссылка на статью "Виды, типы тестирования, техники тест-дизайна. Статья. Habrahabr" Геннадия Мищевского. Я списалась с автором и запросила активную ссылку на актуальную версию статьи. 

Работающая ссылка на доработанную версию https://dou.ua/forums/topic/13389/

Скриншот переписки с Генадием в habr 
<img width="701" alt="image" src="https://user-images.githubusercontent.com/29330744/115540462-1e85e500-a2af-11eb-9119-ac4fab39cc4c.png">

**Comment by volekerb** [comment]
Отлично, спасибо!
